FROM ubuntu

# arguments
ARG UNITY_SRC="https://github.com/ThrowTheSwitch/Unity/archive/refs/tags/v2.6.1.tar.gz"

# set as no user interface (pure terminal interaction)
ENV DEBIAN_FRONTEND=non-interactive

# install essential packages
RUN \
    apt update -y && apt upgrade -y && apt install -y \
# basic tools
    wget \
# build tools
    cmake \ 
    ninja-build \
# compilers
    g++ \
    gcc 

# set working directory to top level of linux 
WORKDIR /

# set commands to run from bash
CMD "/bin/bash"
SHELL ["/bin/bash", "-c"]

# install latest Unity test framework
RUN \ 
mkdir unity && \ 
pushd unity && \ 
    mkdir tmp && \ 
    pushd tmp && \ 
        wget ${UNITY_SRC} && \ 
        tar -xvzf *.tar.gz  && \ 
        cp -v -r */src/*[hc] .. && \ 
    popd && \ 
    rm -rf tmp && \ 
popd 

RUN echo "hello world"