FROM ubuntu

# set as no user interface (pure terminal interaction)
ENV DEBIAN_FRONTEND=non-interactive

# install essential packages
RUN \
    apt update -y && apt upgrade -y && apt install -y \
# basic tools
    wget \
    python3 \
    python-is-python3 \
# build tools
    cmake \ 
    ninja-build \
# compilers
    g++ \
    gcc 

# set working directory to top level of linux 
WORKDIR /

# set commands to run from bash
CMD "/bin/bash"

# build and run tests
RUN echo "hello world"